version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth:
    build: ./services/auth
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: authuser
      DB_PASSWORD: authpass
      DB_NAME: authdb
    depends_on:
      - db
  users:
    build: ./services/users
    environment:
      - DB_HOST=db
      - DB_USER=authuser
      - DB_PASSWORD=authpass
      - DB_NAME=authdb
      - DB_PORT=5432
    depends_on:
      - db

  products:
    build: ./services/products

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - products

volumes:
  pgdata:
