version: '3.8'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth:
    build: ./services/auth
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: authuser
      DB_PASSWORD: authpass
      DB_NAME: authdb
      JWT_SECRET: your_jwt_secret_key
    depends_on:
      - db
    

  products:
    build: ./services/products

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - products

volumes:
  pgdata:
